# docker-compose.yml
version: "3.7"

services:
  caddy:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment SERVER_NAME to disable HTTPS (used for development)
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiKiJdfX0.xnnA-vamHl3AMdAFgpk8677Hkt62QiaDbgPGsgutyQ0'
      MERCURE_SUBSCRIBER_JWT_KEY: 'eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiKiJdfX0.xnnA-vamHl3AMdAFgpk8677Hkt62QiaDbgPGsgutyQ0'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - "3000:80"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
